# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LMEMIXEDQUICK <- function(MyData, kinIn = 1L, covVarRead = 0L, epsilon = 1e-6, remliter = 30L) {
    .Call(`_KLMMAL_LMEMIXEDQUICK`, MyData, kinIn, covVarRead, epsilon, remliter)
}

